name:                hello-servant
version:             0.1.0.0
author:              "Tomas Aschan"
maintainer:          "1550920+tomasaschan@users.noreply.github.com"
copyright:           "2020 Tomas Aschan"

dependencies:
  - base

library:
  source-dirs: src/lib
  ghc-options:
    - -Wall
  dependencies:
    - aeson
    - hodatime
    - lens
    - mtl
    - servant
    - servant-server
    - sort
    - text
  
executables:
  server:
    main:                Main.hs
    source-dirs:         src/app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - hello-servant
      - servant
      - servant-server
      - wai
      - warp

tests:
  unit:
    main:                Spec.hs
    source-dirs:         test/lib
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - hello-servant

default-extensions:
  - DataKinds
  - DeriveGeneric
  - OverloadedStrings
  - TypeOperators
  